import { Exercise } from '@/types/exercise';

export const DEFAULT_EXERCISES: Exercise[] = [
  // PEITO (chest)
  { id: 'ex-chest-01', name: 'Supino Reto com Barra', muscleGroup: 'chest', category: 'strength', mediaFilename: 'barbell_bench_press.mp4', instructions: 'Deite-se no banco, pegue a barra com pegada pouco mais aberta que os ombros. Desça controlando até tocar levemente o peito. Empurre de volta estendendo os braços sem travar os cotovelos.', createdAt: 0 },
  { id: 'ex-chest-02', name: 'Supino Reto com Halteres', muscleGroup: 'chest', category: 'strength', mediaFilename: 'dumbbell_bench_press.mp4', instructions: 'Deitado no banco, segure os halteres ao lado do peito com palmas para frente. Empurre para cima até quase encostar os halteres. Desça controladamente.', createdAt: 0 },
  { id: 'ex-chest-03', name: 'Supino Inclinado com Halteres', muscleGroup: 'chest', category: 'strength', mediaFilename: 'dumbbell_incline_bench_press.mp4', instructions: 'Banco inclinado 30-45°. Halteres ao lado do peito superior. Empurre para cima e desça com controle.', createdAt: 0 },
  { id: 'ex-chest-04', name: 'Crucifixo com Halteres', muscleGroup: 'chest', category: 'strength', mediaFilename: 'dumbbell_chest_fly.mp4', instructions: 'Deitado no banco, braços estendidos com leve flexão no cotovelo. Abra em arco até sentir alongamento no peito. Retorne na mesma trajetória.', createdAt: 0 },
  { id: 'ex-chest-05', name: 'Crucifixo Inclinado com Halteres', muscleGroup: 'chest', category: 'strength', mediaFilename: 'dumbbell_incline_chest_flys.mp4', instructions: 'Banco inclinado. Braços semi-flexionados, abra em arco amplo e retorne contraindo o peito.', createdAt: 0 },
  { id: 'ex-chest-06', name: 'Flexão de Braço', muscleGroup: 'chest', category: 'calisthenics', mediaFilename: 'pushup.mp4', instructions: 'Mãos pouco mais abertas que os ombros, corpo alinhado. Desça até o peito quase tocar o chão. Empurre de volta mantendo o core ativo.', createdAt: 0 },
  { id: 'ex-chest-07', name: 'Flexão Diamante', muscleGroup: 'chest', category: 'calisthenics', mediaFilename: 'diamond_pushup.mp4', instructions: 'Mãos juntas formando um triângulo sob o peito. Desça e suba mantendo cotovelos próximos ao corpo.', createdAt: 0 },

  // COSTAS (back)
  { id: 'ex-back-01', name: 'Remada Curvada com Barra', muscleGroup: 'back', category: 'strength', mediaFilename: 'barbell_bent_over_row.mp4', instructions: 'Tronco inclinado à frente 45°, coluna neutra. Puxe a barra em direção ao abdômen aproximando as escápulas. Desça controlado.', createdAt: 0 },
  { id: 'ex-back-02', name: 'Remada Unilateral com Halter', muscleGroup: 'back', category: 'strength', mediaFilename: 'dumbbell_kneeling_single_arm_row.mp4', instructions: 'Apoiado no banco com um joelho e uma mão. Puxe o halter em direção à cintura contraindo a escápula. Estenda o braço completamente na descida.', createdAt: 0 },
  { id: 'ex-back-03', name: 'Remada Inclinada no Banco', muscleGroup: 'back', category: 'strength', mediaFilename: 'dumbbell_laying_incline_row.mp4', instructions: 'Deitado de bruços em banco inclinado. Puxe os halteres até a linha do tronco, contraindo escápulas. Desça controlado.', createdAt: 0 },
  { id: 'ex-back-04', name: 'Barra Fixa (Pull-up)', muscleGroup: 'back', category: 'calisthenics', mediaFilename: 'pullup.mp4', instructions: 'Pegada pronada, mãos pouco mais abertas que os ombros. Puxe até o queixo passar a barra. Desça com controle até braços estendidos.', createdAt: 0 },
  { id: 'ex-back-05', name: 'Barra Supinada (Chin-up)', muscleGroup: 'back', category: 'calisthenics', mediaFilename: 'chinup.mp4', instructions: 'Pegada supinada na largura dos ombros. Puxe trazendo o peito em direção à barra. Desça controlado.', createdAt: 0 },
  { id: 'ex-back-06', name: 'Remada Australiana', muscleGroup: 'back', category: 'calisthenics', mediaFilename: 'australian_pullup.mp4', instructions: 'Corpo sob barra baixa, calcanhares no chão, corpo reto. Puxe o peito até a barra e retorne estendendo os braços.', createdAt: 0 },

  // OMBROS (shoulder)
  { id: 'ex-shoulder-01', name: 'Desenvolvimento Militar com Halteres', muscleGroup: 'shoulder', category: 'strength', mediaFilename: 'dumbbell_shoulder_press.mp4', instructions: 'Sentado ou em pé, halteres ao nível dos ombros. Empurre para cima até quase estender os braços. Desça controlado.', createdAt: 0 },
  { id: 'ex-shoulder-02', name: 'Elevação Lateral', muscleGroup: 'shoulder', category: 'strength', mediaFilename: 'dumbbell_lateral_raise.mp4', instructions: 'Em pé, halteres ao lado do corpo, cotovelos levemente flexionados. Eleve os braços até a linha dos ombros. Desça controlado.', createdAt: 0 },
  { id: 'ex-shoulder-03', name: 'Elevação Frontal', muscleGroup: 'shoulder', category: 'strength', mediaFilename: 'dumbbell_front_raise.mp4', instructions: 'Em pé, halteres à frente das coxas. Eleve um braço por vez até a altura dos ombros, mantendo leve flexão no cotovelo. Desça controlado.', createdAt: 0 },
  { id: 'ex-shoulder-04', name: 'Desenvolvimento Arnold', muscleGroup: 'shoulder', category: 'strength', mediaFilename: 'arnold_press.mp4', instructions: 'Comece com halteres à frente, palmas voltadas para você. Gire os punhos enquanto empurra para cima. Desça invertendo o movimento.', createdAt: 0 },
  { id: 'ex-shoulder-05', name: 'Pike Push-up', muscleGroup: 'shoulder', category: 'calisthenics', mediaFilename: 'pike_pushup.mp4', instructions: 'Posição de V invertido com quadril elevado. Desça o topo da cabeça em direção ao chão flexionando os cotovelos. Empurre de volta.', createdAt: 0 },

  // BÍCEPS (biceps)
  { id: 'ex-biceps-01', name: 'Rosca Direta com Halteres', muscleGroup: 'biceps', category: 'strength', mediaFilename: 'dumbbell_curl.mp4', instructions: 'Em pé, halteres ao lado do corpo com palmas para frente. Flexione os cotovelos trazendo os halteres em direção aos ombros. Desça controlado.', createdAt: 0 },
  { id: 'ex-biceps-02', name: 'Rosca Alternada', muscleGroup: 'biceps', category: 'strength', mediaFilename: 'dumbbell_alternating_curl.mp4', instructions: 'Alterne as flexões de braço, um de cada vez, com palma supinada. Mantenha o cotovelo fixo ao lado do corpo.', createdAt: 0 },
  { id: 'ex-biceps-03', name: 'Rosca Martelo', muscleGroup: 'biceps', category: 'strength', mediaFilename: 'dumbbell_hammer_curl.mp4', instructions: 'Halteres com pegada neutra (palmas voltadas uma para outra). Flexione mantendo os punhos neutros. Desça controlado.', createdAt: 0 },
  { id: 'ex-biceps-04', name: 'Rosca Scott Unilateral', muscleGroup: 'biceps', category: 'strength', mediaFilename: 'dumbbell_single_arm_preacher_curl.mp4', instructions: 'Braço apoiado no banco Scott, halter em pegada supinada. Flexione sem mover o cotovelo. Desça até quase estender o braço.', createdAt: 0 },
  { id: 'ex-biceps-05', name: 'Rosca Concentrada', muscleGroup: 'biceps', category: 'strength', mediaFilename: 'dumbbell_concentration_curl.mp4', instructions: 'Sentado, cotovelo apoiado na parte interna da coxa. Flexione o braço em direção ao ombro mantendo o cotovelo fixo.', createdAt: 0 },

  // TRÍCEPS (triceps)
  { id: 'ex-triceps-01', name: 'Tríceps Testa com Halteres', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'dumbbell_skullcrusher.mp4', instructions: 'Deitado no banco, halteres acima do peito com braços estendidos. Flexione só os cotovelos levando os halteres próximos à testa. Estenda de volta.', createdAt: 0 },
  { id: 'ex-triceps-02', name: 'Extensão de Tríceps Acima da Cabeça', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'dumbbell_overhead_tricep_extension.mp4', instructions: 'Sentado ou em pé, segure um halter com as duas mãos acima da cabeça. Flexione os cotovelos descendo o halter atrás da cabeça. Estenda de volta.', createdAt: 0 },
  { id: 'ex-triceps-03', name: 'Tríceps Coice', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'dumbbell_tricep_kickback.mp4', instructions: 'Tronco inclinado, cotovelo flexionado próximo ao tronco. Estenda o braço para trás até a linha do ombro. Retorne controlado.', createdAt: 0 },
  { id: 'ex-triceps-04', name: 'Mergulho entre Bancos', muscleGroup: 'triceps', category: 'calisthenics', mediaFilename: 'bench_dips.mp4', instructions: 'Mãos em um banco atrás de você, pés no chão ou em outro banco. Desça flexionando os cotovelos. Empurre de volta.', createdAt: 0 },
  { id: 'ex-triceps-05', name: 'Flexão Fechada', muscleGroup: 'triceps', category: 'calisthenics', mediaFilename: 'close_grip_pushup.mp4', instructions: 'Flexão com mãos próximas entre si, cotovelos colados ao corpo na descida. Empurre de volta contraindo o tríceps.', createdAt: 0 },

  // PERNAS (legs)
  { id: 'ex-legs-01', name: 'Agachamento Livre com Barra', muscleGroup: 'legs', category: 'strength', mediaFilename: 'barbell_squat.mp4', instructions: 'Barra apoiada nos trapézios, pés na largura dos ombros. Desça flexionando quadril e joelhos até coxas paralelas ao chão. Suba empurrando o chão.', createdAt: 0 },
  { id: 'ex-legs-02', name: 'Agachamento Goblet', muscleGroup: 'legs', category: 'strength', mediaFilename: 'dumbbell_goblet_squat.mp4', instructions: 'Segure um halter verticalmente contra o peito. Agache mantendo o tronco ereto. Suba empurrando pelos calcanhares.', createdAt: 0 },
  { id: 'ex-legs-03', name: 'Afundo com Halteres', muscleGroup: 'legs', category: 'strength', mediaFilename: 'dumbbell_lunge.mp4', instructions: 'Halteres ao lado do corpo. Dê um passo à frente e desça flexionando os dois joelhos em 90°. Empurre de volta à posição inicial.', createdAt: 0 },
  { id: 'ex-legs-04', name: 'Stiff com Halteres', muscleGroup: 'legs', category: 'strength', mediaFilename: 'dumbbell_stiff_deadlift.mp4', instructions: 'Halteres à frente das coxas, joelhos levemente flexionados. Desça inclinando o quadril para trás, costas neutras, até sentir posteriores. Suba contraindo glúteos.', createdAt: 0 },
  { id: 'ex-legs-05', name: 'Elevação de Panturrilha', muscleGroup: 'legs', category: 'strength', mediaFilename: 'dumbbell_calf_raise.mp4', instructions: 'Em pé com halteres, suba na ponta dos pés contraindo panturrilhas. Desça controlado até a posição inicial.', createdAt: 0 },
  { id: 'ex-legs-06', name: 'Agachamento Búlgaro', muscleGroup: 'legs', category: 'strength', mediaFilename: 'dumbbell_bulgarian_split_squat.mp4', instructions: 'Pé de trás apoiado em banco, halteres ao lado. Desça flexionando o joelho da frente. Suba empurrando pela perna da frente.', createdAt: 0 },
  { id: 'ex-legs-07', name: 'Agachamento Pistol', muscleGroup: 'legs', category: 'calisthenics', mediaFilename: 'pistol_squat.mp4', instructions: 'Agachamento em uma perna só, outra perna estendida à frente. Desça controlado e suba com força na perna de apoio.', createdAt: 0 },

  // CORE
  { id: 'ex-core-01', name: 'Prancha Abdominal', muscleGroup: 'core', category: 'calisthenics', mediaFilename: 'plank.mp4', instructions: 'Apoio nos antebraços e pontas dos pés, corpo alinhado em linha reta. Contraia core e glúteos. Mantenha pelo tempo determinado.', createdAt: 0 },
  { id: 'ex-core-02', name: 'Prancha Lateral', muscleGroup: 'core', category: 'calisthenics', mediaFilename: 'side_plank.mp4', instructions: 'Apoio em um antebraço e lateral do pé, corpo alinhado. Quadril elevado. Mantenha contraindo oblíquos.', createdAt: 0 },
  { id: 'ex-core-03', name: 'Abdominal Crunch', muscleGroup: 'core', category: 'calisthenics', mediaFilename: 'crunch.mp4', instructions: 'Deitado de costas, joelhos flexionados. Eleve o tronco até as escápulas saírem do chão contraindo o abdômen. Desça controlado.', createdAt: 0 },
  { id: 'ex-core-04', name: 'Elevação de Pernas', muscleGroup: 'core', category: 'calisthenics', mediaFilename: 'leg_raise.mp4', instructions: 'Deitado de costas, pernas estendidas. Eleve as pernas até 90° mantendo a lombar no chão. Desça controlado sem tocar o chão.', createdAt: 0 },
  { id: 'ex-core-05', name: 'Russian Twist', muscleGroup: 'core', category: 'calisthenics', mediaFilename: 'russian_twist.mp4', instructions: 'Sentado com tronco inclinado e pés elevados. Gire o tronco de um lado para o outro tocando as mãos (ou peso) no chão.', createdAt: 0 },

  // CORPO INTEIRO (full_body)
  { id: 'ex-fullbody-01', name: 'Burpee', muscleGroup: 'full_body', category: 'calisthenics', mediaFilename: 'burpee.mp4', instructions: 'Desça ao chão, faça uma flexão, recolha as pernas, salte para cima. Repita fluidamente.', createdAt: 0 },
  { id: 'ex-fullbody-02', name: 'Mountain Climber', muscleGroup: 'full_body', category: 'calisthenics', mediaFilename: 'mountain_climber.mp4', instructions: 'Em posição de prancha alta, traga os joelhos alternadamente em direção ao peito em ritmo acelerado.', createdAt: 0 },
  { id: 'ex-fullbody-03', name: 'Bear Crawl', muscleGroup: 'full_body', category: 'calisthenics', mediaFilename: 'bear_crawl.mp4', instructions: 'Apoio nas mãos e pés com joelhos próximos ao chão sem tocar. Avance com braço e perna opostos simultaneamente.', createdAt: 0 },
  { id: 'ex-fullbody-04', name: 'Thruster com Halteres', muscleGroup: 'full_body', category: 'strength', mediaFilename: 'dumbbell_thruster.mp4', instructions: 'Halteres na altura dos ombros. Agache e, ao subir, empurre os halteres acima da cabeça em um movimento único.', createdAt: 0 },
];

const NOW = Date.now();
DEFAULT_EXERCISES.forEach(ex => { ex.createdAt = NOW; });
