import { Exercise } from '@/types/exercise';

export const DEFAULT_EXERCISES: Exercise[] = [
  // PEITO (chest) — 22
  { id: 'ex-chest-01', name: 'Supino Reto com Barra', muscleGroup: 'chest', category: 'strength', mediaFilename: 'barbell_bench_press.mp4', instructions: 'Deite no banco, pegue a barra com pegada pouco mais aberta que os ombros. Desça controlado até tocar levemente o peito. Empurre estendendo os braços sem travar os cotovelos.', createdAt: 0 },
  { id: 'ex-chest-02', name: 'Supino Inclinado com Barra', muscleGroup: 'chest', category: 'strength', mediaFilename: 'barbell_incline_bench_press.mp4', instructions: 'Banco inclinado 30-45°. Pegue a barra com pegada pouco mais aberta que os ombros. Desça até a parte superior do peito. Empurre estendendo os braços.', createdAt: 0 },
  { id: 'ex-chest-03', name: 'Supino Reto com Halteres', muscleGroup: 'chest', category: 'strength', mediaFilename: 'dumbbell_bench_press.mp4', instructions: 'Deitado no banco, halteres ao lado do peito com palmas para frente. Empurre para cima até quase encostar os halteres. Desça controlado.', createdAt: 0 },
  { id: 'ex-chest-04', name: 'Supino Inclinado com Halteres', muscleGroup: 'chest', category: 'strength', mediaFilename: 'dumbbell_incline_bench_press.mp4', instructions: 'Banco inclinado 30-45°. Halteres ao lado do peito superior. Empurre para cima e desça com controle.', createdAt: 0 },
  { id: 'ex-chest-05', name: 'Supino Declinado com Halteres', muscleGroup: 'chest', category: 'strength', mediaFilename: 'dumbbell_decline_bench_press.mp4', instructions: 'Banco declinado, pés fixos. Halteres ao lado do peito. Empurre para cima e desça com controle.', createdAt: 0 },
  { id: 'ex-chest-06', name: 'Supino Declinado Alternado com Halteres', muscleGroup: 'chest', category: 'strength', mediaFilename: 'dumbbell_decline_alternating_single_arm_press.mp4', instructions: 'Banco declinado. Empurre um halter por vez alternadamente, mantendo o outro estabilizado em cima.', createdAt: 0 },
  { id: 'ex-chest-07', name: 'Crucifixo com Halteres', muscleGroup: 'chest', category: 'strength', mediaFilename: 'dumbbell_chest_fly.mp4', instructions: 'Deitado no banco, braços estendidos com leve flexão no cotovelo. Abra em arco até sentir alongamento no peito. Retorne na mesma trajetória.', createdAt: 0 },
  { id: 'ex-chest-08', name: 'Crucifixo Inclinado com Halteres', muscleGroup: 'chest', category: 'strength', mediaFilename: 'dumbbell_incline_chest_fly.mp4', instructions: 'Banco inclinado, braços semi-flexionados. Abra em arco amplo e retorne contraindo o peito.', createdAt: 0 },
  { id: 'ex-chest-09', name: 'Crucifixo Declinado com Halteres', muscleGroup: 'chest', category: 'strength', mediaFilename: 'dumbbell_decline_chest_fly.mp4', instructions: 'Banco declinado, halteres acima do peito com cotovelos semi-flexionados. Abra em arco e retorne contraindo o peito.', createdAt: 0 },
  { id: 'ex-chest-10', name: 'Mergulho com Peso', muscleGroup: 'chest', category: 'strength', mediaFilename: 'dumbbell_weighted_dip.mp4', instructions: 'Em paralelas, com halter pendurado na cintura. Tronco inclinado à frente para focar no peito. Desça flexionando cotovelos e empurre de volta.', createdAt: 0 },
  { id: 'ex-chest-11', name: 'Supino na Polia', muscleGroup: 'chest', category: 'strength', mediaFilename: 'cable_chestpress.mp4', instructions: 'Em pé entre as polias, pegadores na altura do peito. Empurre os pegadores à frente até estender os braços. Volte controlado.', createdAt: 0 },
  { id: 'ex-chest-12', name: 'Supino Declinado na Polia', muscleGroup: 'chest', category: 'strength', mediaFilename: 'cable_decline_bench_press.mp4', instructions: 'No banco declinado entre as polias, empurre os pegadores acima do peito até estender os braços. Volte controlado.', createdAt: 0 },
  { id: 'ex-chest-13', name: 'Crucifixo Declinado na Polia', muscleGroup: 'chest', category: 'strength', mediaFilename: 'cable_decline_bench_chest_fly.mp4', instructions: 'Deitado em banco declinado entre as polias, braços abertos com leve flexão. Junte os pegadores à frente do peito contraindo. Abra controlado.', createdAt: 0 },
  { id: 'ex-chest-14', name: 'Crucifixo na Polia (Pec Fly)', muscleGroup: 'chest', category: 'strength', mediaFilename: 'cable_pec_fly.mp4', instructions: 'Em pé, pegadores nas polias altas. Junte as mãos à frente do corpo em arco contraindo o peito. Volte controlado.', createdAt: 0 },
  { id: 'ex-chest-15', name: 'Voador (Pec Deck) na Máquina', muscleGroup: 'chest', category: 'strength', mediaFilename: 'machine_bent_arm_pec_fly.mp4', instructions: 'Sentado na máquina, antebraços nos apoios. Junte os apoios à frente do peito contraindo. Volte controlado.', createdAt: 0 },
  { id: 'ex-chest-16', name: 'Supino Declinado na Máquina', muscleGroup: 'chest', category: 'strength', mediaFilename: 'machine_plate_loaded_decline_chest_press.mp4', instructions: 'Sentado/deitado na máquina declinada, empurre as alavancas até estender os braços. Volte com controle.', createdAt: 0 },
  { id: 'ex-chest-17', name: 'Flexão de Braço', muscleGroup: 'chest', category: 'calisthenics', mediaFilename: 'Bodyweight_push_up.mp4', instructions: 'Mãos pouco mais abertas que os ombros, corpo alinhado. Desça até o peito quase tocar o chão. Empurre de volta mantendo o core ativo.', createdAt: 0 },
  { id: 'ex-chest-18', name: 'Flexão Inclinada', muscleGroup: 'chest', category: 'calisthenics', mediaFilename: 'Bodyweight_incline_push_up.mp4', instructions: 'Mãos apoiadas em superfície elevada (banco/cadeira), corpo alinhado em diagonal. Desça e suba mantendo core firme.', createdAt: 0 },
  { id: 'ex-chest-19', name: 'Flexão Declinada', muscleGroup: 'chest', category: 'calisthenics', mediaFilename: 'Bodyweight_decline_push_up.mp4', instructions: 'Pés apoiados em superfície elevada, mãos no chão. Desça flexionando cotovelos. Empurre de volta — foca peito superior.', createdAt: 0 },
  { id: 'ex-chest-20', name: 'Flexão com Joelhos', muscleGroup: 'chest', category: 'calisthenics', mediaFilename: 'bodyweight_knee_push_ups.mp4', instructions: 'Variação iniciante: joelhos no chão. Desça o peito mantendo o tronco alinhado quadril-ombros. Empurre de volta.', createdAt: 0 },
  { id: 'ex-chest-21', name: 'Flexão Inclinada com Joelhos', muscleGroup: 'chest', category: 'calisthenics', mediaFilename: 'bodyweight_incline_knee_push_up.mp4', instructions: 'Mãos elevadas + joelhos no chão. Variação muito acessível: ótima para iniciantes ganharem força no peito.', createdAt: 0 },
  { id: 'ex-chest-22', name: 'Flexão Explosiva', muscleGroup: 'chest', category: 'calisthenics', mediaFilename: 'bodyweight_explosive_push_up.mp4', instructions: 'Desça como flexão normal, e na subida empurre forte para tirar as mãos do chão. Pouse suave e repita.', createdAt: 0 },

  // COSTAS (back) — 10
  { id: 'ex-back-01', name: 'Remada Curvada com Barra', muscleGroup: 'back', category: 'strength', mediaFilename: 'barbell_bent_over_row.mp4', instructions: 'Tronco inclinado 45°, coluna neutra. Puxe a barra em direção ao abdômen aproximando as escápulas. Desça controlado.', createdAt: 0 },
  { id: 'ex-back-02', name: 'Remada Unilateral com Halter', muscleGroup: 'back', category: 'strength', mediaFilename: 'dumbbell_kneeling_single_arm_row.mp4', instructions: 'Apoiado no banco com um joelho e uma mão. Puxe o halter em direção à cintura contraindo a escápula. Estenda completo na descida.', createdAt: 0 },
  { id: 'ex-back-03', name: 'Remada Inclinada no Banco', muscleGroup: 'back', category: 'strength', mediaFilename: 'dumbbell_laying_incline_row.mp4', instructions: 'Deitado de bruços em banco inclinado. Puxe os halteres até a linha do tronco, contraindo escápulas. Desça controlado.', createdAt: 0 },
  { id: 'ex-back-04', name: 'Remada T (Máquina)', muscleGroup: 'back', category: 'strength', mediaFilename: 'machine_plate_loaded_t_bar_row.mp4', instructions: 'Posição inclinada à frente, peito apoiado. Puxe a alavanca em direção ao tronco contraindo as costas. Desça controlado.', createdAt: 0 },
  { id: 'ex-back-05', name: 'Puxada Frontal (Pulldown)', muscleGroup: 'back', category: 'strength', mediaFilename: 'machine_pulldown.mp4', instructions: 'Sentado na máquina, pegada pronada larga. Puxe a barra até a parte superior do peito. Volte estendendo os braços controlado.', createdAt: 0 },
  { id: 'ex-back-06', name: 'Remada Sentado na Polia', muscleGroup: 'back', category: 'strength', mediaFilename: 'machine_seated_cable_row.mp4', instructions: 'Sentado, joelhos semi-flexionados, tronco ereto. Puxe o pegador em direção ao abdômen aproximando escápulas. Estenda controlado.', createdAt: 0 },
  { id: 'ex-back-07', name: 'Pullover na Polia', muscleGroup: 'back', category: 'strength', mediaFilename: 'cable_pullover.mp4', instructions: 'Em pé de frente para a polia alta, braços estendidos à frente. Puxe a barra em arco para baixo até a coxa, sem dobrar os cotovelos.', createdAt: 0 },
  { id: 'ex-back-08', name: 'Barra Fixa Assistida (Máquina)', muscleGroup: 'back', category: 'strength', mediaFilename: 'machine_assisted_pull_up.mp4', instructions: 'Joelho ou pés apoiados na almofada de assistência. Faça pull-up regular — a máquina ajuda no peso. Desça controlado.', createdAt: 0 },
  { id: 'ex-back-09', name: 'Barra Fixa (Pull-up)', muscleGroup: 'back', category: 'calisthenics', mediaFilename: 'bodyweight_pullup.mp4', instructions: 'Pegada pronada, mãos pouco mais abertas que os ombros. Puxe até o queixo passar a barra. Desça com controle até braços estendidos.', createdAt: 0 },
  { id: 'ex-back-10', name: 'Barra Supinada (Chin-up)', muscleGroup: 'back', category: 'calisthenics', mediaFilename: 'bodyweight_chinup.mp4', instructions: 'Pegada supinada na largura dos ombros. Puxe trazendo o peito em direção à barra. Desça controlado.', createdAt: 0 },

  // OMBROS (shoulder) — 6
  { id: 'ex-shoulder-01', name: 'Desenvolvimento com Halteres', muscleGroup: 'shoulder', category: 'strength', mediaFilename: 'dumbbell_overhead_press.mp4', instructions: 'Em pé, halteres ao nível dos ombros. Empurre para cima até quase estender os braços. Desça controlado até a altura dos ombros.', createdAt: 0 },
  { id: 'ex-shoulder-02', name: 'Desenvolvimento Sentado com Halteres', muscleGroup: 'shoulder', category: 'strength', mediaFilename: 'dumbbell_seated_overhead_press.mp4', instructions: 'Sentado com encosto, halteres ao nível dos ombros. Empurre para cima até quase estender os braços. Desça controlado.', createdAt: 0 },
  { id: 'ex-shoulder-03', name: 'Desenvolvimento na Máquina (Pegada Neutra)', muscleGroup: 'shoulder', category: 'strength', mediaFilename: 'machine_neutral_overhead_press.mp4', instructions: 'Sentado na máquina, pegadores em pegada neutra. Empurre para cima estendendo os braços. Desça controlado.', createdAt: 0 },
  { id: 'ex-shoulder-04', name: 'Elevação Lateral com Halteres', muscleGroup: 'shoulder', category: 'strength', mediaFilename: 'dumbbell_lateral_raise.mp4', instructions: 'Em pé, halteres ao lado do corpo, cotovelos levemente flexionados. Eleve os braços até a linha dos ombros. Desça controlado.', createdAt: 0 },
  { id: 'ex-shoulder-05', name: 'Elevação Frontal com Halteres', muscleGroup: 'shoulder', category: 'strength', mediaFilename: 'dumbbell_front_raise.mp4', instructions: 'Em pé, halteres à frente das coxas. Eleve até a altura dos ombros mantendo leve flexão no cotovelo. Desça controlado.', createdAt: 0 },
  { id: 'ex-shoulder-06', name: 'Pike Push-up', muscleGroup: 'shoulder', category: 'calisthenics', mediaFilename: 'bodyweight_pike_press.mp4', instructions: 'Posição de V invertido com quadril elevado. Desça o topo da cabeça em direção ao chão flexionando os cotovelos. Empurre de volta.', createdAt: 0 },

  // BÍCEPS (biceps) — 9
  { id: 'ex-biceps-01', name: 'Rosca Direta com Halteres', muscleGroup: 'biceps', category: 'strength', mediaFilename: 'dumbbell_curl.mp4', instructions: 'Em pé, halteres ao lado do corpo com palmas para frente. Flexione os cotovelos trazendo os halteres em direção aos ombros. Desça controlado.', createdAt: 0 },
  { id: 'ex-biceps-02', name: 'Rosca Alternada com Halteres', muscleGroup: 'biceps', category: 'strength', mediaFilename: 'Dumbbells_dumbbell_curl.mp4', instructions: 'Em pé, halteres ao lado do corpo. Flexione um braço de cada vez alternadamente, mantendo o cotovelo fixo ao lado do corpo.', createdAt: 0 },
  { id: 'ex-biceps-03', name: 'Rosca Martelo', muscleGroup: 'biceps', category: 'strength', mediaFilename: 'dumbbell_hammer_curl.mp4', instructions: 'Halteres com pegada neutra (palmas voltadas uma para outra). Flexione mantendo os punhos neutros. Desça controlado.', createdAt: 0 },
  { id: 'ex-biceps-04', name: 'Rosca Concentrada', muscleGroup: 'biceps', category: 'strength', mediaFilename: 'dumbbell_concentration_curl.mp4', instructions: 'Sentado, cotovelo apoiado na parte interna da coxa. Flexione o braço em direção ao ombro mantendo o cotovelo fixo.', createdAt: 0 },
  { id: 'ex-biceps-05', name: 'Rosca Scott Unilateral', muscleGroup: 'biceps', category: 'strength', mediaFilename: 'dumbbell_single_arm_preacher_curl.mp4', instructions: 'Braço apoiado no banco Scott, halter em pegada supinada. Flexione sem mover o cotovelo. Desça até quase estender o braço.', createdAt: 0 },
  { id: 'ex-biceps-06', name: 'Rosca Direta na Polia', muscleGroup: 'biceps', category: 'strength', mediaFilename: 'cable_bar_curl.mp4', instructions: 'Em pé de frente para a polia baixa, barra em pegada supinada. Flexione os cotovelos em direção aos ombros. Desça controlado.', createdAt: 0 },
  { id: 'ex-biceps-07', name: 'Rosca Bayesian na Polia', muscleGroup: 'biceps', category: 'strength', mediaFilename: 'cable_bayesian_curl.mp4', instructions: 'De costas para a polia baixa, dê um passo à frente. Cotovelo atrás do tronco. Flexione o braço sem mover o cotovelo, alongando o bíceps.', createdAt: 0 },
  { id: 'ex-biceps-08', name: 'Rosca Martelo na Corda', muscleGroup: 'biceps', category: 'strength', mediaFilename: 'cable_rope_hammer_curl.mp4', instructions: 'Em pé na polia baixa com corda. Pegada neutra. Flexione os cotovelos trazendo as mãos aos ombros, contraindo bíceps e braquial.', createdAt: 0 },
  { id: 'ex-biceps-09', name: 'Rosca Invertida na Barra', muscleGroup: 'biceps', category: 'calisthenics', mediaFilename: 'bodyweight_close_grip_inverted_curl.mp4', instructions: 'Sob barra baixa em pegada supinada fechada, corpo reto. Puxe o peito em direção à barra contraindo bíceps. Desça controlado.', createdAt: 0 },

  // TRÍCEPS (triceps) — 13
  { id: 'ex-triceps-01', name: 'Tríceps Testa com Halteres', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'dumbbell_skullcrusher.mp4', instructions: 'Deitado no banco, halteres acima do peito com braços estendidos. Flexione só os cotovelos levando os halteres próximos à testa. Estenda de volta.', createdAt: 0 },
  { id: 'ex-triceps-02', name: 'Tríceps Francês com Halter', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'dumbbell_overhead_tricep_extension.mp4', instructions: 'Sentado ou em pé, halter com as duas mãos acima da cabeça. Flexione os cotovelos descendo o halter atrás da cabeça. Estenda de volta.', createdAt: 0 },
  { id: 'ex-triceps-03', name: 'Tríceps Francês na Máquina', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'machine_overhead_tricep_extension.mp4', instructions: 'Sentado na máquina, mãos nos pegadores acima da cabeça. Estenda os braços para cima/frente. Volte com controle.', createdAt: 0 },
  { id: 'ex-triceps-04', name: 'Tríceps Pulley', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'cable_push_down.mp4', instructions: 'Em pé de frente para a polia alta, cotovelos colados ao tronco. Estenda os antebraços para baixo até travar. Volte controlado.', createdAt: 0 },
  { id: 'ex-triceps-05', name: 'Tríceps Pulley (Variação)', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'cable_push_downs.mp4', instructions: 'Variação do pushdown na polia. Foco em isolar o tríceps mantendo os cotovelos fixos ao lado do tronco.', createdAt: 0 },
  { id: 'ex-triceps-06', name: 'Tríceps Pulley com Barra (Rolling)', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'cable_bar_rolling_pushdown.mp4', instructions: 'Variação rolling: na descida flexione bem o ombro, deixando o cotovelo apontar à frente, depois estenda completo. Aumenta amplitude.', createdAt: 0 },
  { id: 'ex-triceps-07', name: 'Tríceps Pulley com Corda (Rolling)', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'cable_rope_rolling_pushdown.mp4', instructions: 'Polia alta com corda. Movimento rolling com cotovelos à frente na descida e estendendo embaixo. Maior amplitude no tríceps.', createdAt: 0 },
  { id: 'ex-triceps-08', name: 'Tríceps Pulley Unilateral (Rolling)', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'cable_single_arm_rolling_pushdown.mp4', instructions: 'Pegador unilateral na polia alta. Rolling pushdown com um braço por vez. Foco em controle e amplitude.', createdAt: 0 },
  { id: 'ex-triceps-09', name: 'Tríceps Testa na Polia', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'cable_skullcrusher.mp4', instructions: 'Deitado em banco com a polia baixa atrás da cabeça. Pegador com as duas mãos. Estenda os antebraços acima da cabeça e desça controlado.', createdAt: 0 },
  { id: 'ex-triceps-10', name: 'Tríceps Testa na Polia com Barra', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'cable_bar_skullcrusher.mp4', instructions: 'Deitado em banco com polia baixa atrás. Barra em pegada pronada. Estenda os braços e desça a barra próxima à testa controlado.', createdAt: 0 },
  { id: 'ex-triceps-11', name: 'Tríceps Francês na Polia', muscleGroup: 'triceps', category: 'strength', mediaFilename: 'cable_overhead_tricep_extension.mp4', instructions: 'De costas para a polia alta com corda. Mãos atrás da cabeça. Estenda os braços à frente/cima. Volte controlado.', createdAt: 0 },
  { id: 'ex-triceps-12', name: 'Mergulho entre Bancos', muscleGroup: 'triceps', category: 'calisthenics', mediaFilename: 'Bodyweight_bench_dips.mp4', instructions: 'Mãos em um banco atrás de você, pés no chão ou em outro banco. Desça flexionando os cotovelos. Empurre de volta.', createdAt: 0 },
  { id: 'ex-triceps-13', name: 'Mergulho em Paralelas', muscleGroup: 'triceps', category: 'calisthenics', mediaFilename: 'Bodyweight_parralel_bar_dips.mp4', instructions: 'Em paralelas, tronco mais reto para focar tríceps. Desça flexionando cotovelos até 90°. Empurre de volta estendendo os braços.', createdAt: 0 },

  // QUADRÍCEPS (quads) — 9
  { id: 'ex-quads-01', name: 'Agachamento Livre com Barra', muscleGroup: 'quads', category: 'strength', mediaFilename: 'barbell_squat.mp4', instructions: 'Barra apoiada nos trapézios, pés na largura dos ombros. Desça flexionando quadril e joelhos até coxas paralelas. Suba empurrando o chão.', createdAt: 0 },
  { id: 'ex-quads-02', name: 'Agachamento Goblet', muscleGroup: 'quads', category: 'strength', mediaFilename: 'dumbbell_goblet_squat.mp4', instructions: 'Segure um halter verticalmente contra o peito. Agache mantendo o tronco ereto. Suba empurrando pelos calcanhares.', createdAt: 0 },
  { id: 'ex-quads-03', name: 'Afundo Lateral Goblet', muscleGroup: 'quads', category: 'strength', mediaFilename: 'dumbbell_goblet_lateral_lunge.mp4', instructions: 'Halter no peito. Dê um passo amplo lateral, agachando na perna que se moveu. Empurre de volta para o centro.', createdAt: 0 },
  { id: 'ex-quads-04', name: 'Levantamento Terra Sumô', muscleGroup: 'quads', category: 'strength', mediaFilename: 'barbell_sumo_deadlift.mp4', instructions: 'Pés bem afastados, pontas para fora. Pegue a barra entre as pernas com pegada estreita. Suba estendendo joelhos e quadril simultaneamente.', createdAt: 0 },
  { id: 'ex-quads-05', name: 'Agachamento Hack', muscleGroup: 'quads', category: 'strength', mediaFilename: 'machine_hack_squat.mp4', instructions: 'Costas apoiadas na máquina hack, pés na plataforma. Desça flexionando joelhos até 90°. Suba empurrando a plataforma.', createdAt: 0 },
  { id: 'ex-quads-06', name: 'Cadeira Extensora', muscleGroup: 'quads', category: 'strength', mediaFilename: 'machine_leg_extension.mp4', instructions: 'Sentado, calcanhares atrás do rolete. Estenda os joelhos contraindo o quadríceps. Desça controlado.', createdAt: 0 },
  { id: 'ex-quads-07', name: 'Leg Press', muscleGroup: 'quads', category: 'strength', mediaFilename: 'machine_leg_press.mp4', instructions: 'Sentado, pés na plataforma na largura dos ombros. Empurre estendendo os joelhos sem travar. Desça controlado até 90° de flexão.', createdAt: 0 },
  { id: 'ex-quads-08', name: 'Agachamento Livre (Sem Peso)', muscleGroup: 'quads', category: 'calisthenics', mediaFilename: 'bodyweight_squat.mp4', instructions: 'Pés na largura dos ombros. Desça flexionando quadril e joelhos mantendo o tronco ereto. Suba empurrando pelos calcanhares.', createdAt: 0 },
  { id: 'ex-quads-09', name: 'Afundo (Forward Lunge)', muscleGroup: 'quads', category: 'calisthenics', mediaFilename: 'Bodyweight_forward_lunges.mp4', instructions: 'Em pé, dê um passo amplo à frente e desça flexionando os dois joelhos a 90°. Empurre de volta à posição inicial. Alterne as pernas.', createdAt: 0 },

  // POSTERIORES (hamstrings) — 11
  { id: 'ex-hams-01', name: 'Levantamento Terra Romeno com Barra', muscleGroup: 'hamstrings', category: 'strength', mediaFilename: 'barbell_romanian_deadlift.mp4', instructions: 'Barra à frente das coxas, joelhos levemente flexionados. Desça inclinando o quadril para trás, costas neutras. Suba contraindo glúteos e posteriores.', createdAt: 0 },
  { id: 'ex-hams-02', name: 'Levantamento Terra Pegada Snatch', muscleGroup: 'hamstrings', category: 'strength', mediaFilename: 'barbell_snatch_grip_deadlift.mp4', instructions: 'Pegada bem larga (snatch). Desça com quadril para trás e costas neutras. Suba estendendo quadril e joelhos.', createdAt: 0 },
  { id: 'ex-hams-03', name: 'Stiff com Halteres', muscleGroup: 'hamstrings', category: 'strength', mediaFilename: 'dumbbell_romanian_deadlift.mp4', instructions: 'Halteres à frente das coxas, joelhos levemente flexionados. Desça inclinando o quadril para trás até sentir alongamento. Suba contraindo glúteos.', createdAt: 0 },
  { id: 'ex-hams-04', name: 'Stiff Cruzado com Halter', muscleGroup: 'hamstrings', category: 'strength', mediaFilename: 'dumbbell_cross_body_romanian_deadlift.mp4', instructions: 'Apoiado em uma perna, halter na mão oposta cruzando o corpo. Desça com quadril para trás. Suba contraindo glúteos da perna de apoio.', createdAt: 0 },
  { id: 'ex-hams-05', name: 'Bom Dia Goblet com Halter', muscleGroup: 'hamstrings', category: 'strength', mediaFilename: 'dumbbell_goblet_good_morning.mp4', instructions: 'Halter no peito. Joelhos semi-flexionados. Incline o tronco à frente com quadril para trás, costas neutras. Volte estendendo o quadril.', createdAt: 0 },
  { id: 'ex-hams-06', name: 'Reverência (Waiter\'s Bow)', muscleGroup: 'hamstrings', category: 'strength', mediaFilename: 'dumbbell_waiters_bow.mp4', instructions: 'Halter contra o peito como garçom. Incline o tronco à frente com quadril para trás. Volte com glúteos e posteriores.', createdAt: 0 },
  { id: 'ex-hams-07', name: 'Mesa Flexora (Deitado)', muscleGroup: 'hamstrings', category: 'strength', mediaFilename: 'machine_hamstring_curl.mp4', instructions: 'Deitado de bruços, calcanhares no rolete. Flexione os joelhos trazendo o rolete em direção aos glúteos. Desça controlado.', createdAt: 0 },
  { id: 'ex-hams-08', name: 'Mesa Flexora Sentado', muscleGroup: 'hamstrings', category: 'strength', mediaFilename: 'machine_seated_hamstring_curl.mp4', instructions: 'Sentado, panturrilhas sobre o rolete. Flexione os joelhos puxando o rolete para baixo. Volte controlado.', createdAt: 0 },
  { id: 'ex-hams-09', name: 'Flexora em Pé', muscleGroup: 'hamstrings', category: 'strength', mediaFilename: 'machine_standing_hamstring_curl.mp4', instructions: 'Em pé na máquina, flexione um joelho por vez trazendo o calcanhar em direção ao glúteo. Desça controlado.', createdAt: 0 },
  { id: 'ex-hams-10', name: 'Nordic Hamstring (Sem Peso)', muscleGroup: 'hamstrings', category: 'calisthenics', mediaFilename: 'Bodyweight_nordic_hamstring_curl.mp4', instructions: 'Ajoelhado com tornozelos presos. Desça o tronco à frente o mais devagar possível, controlando com os posteriores. Volte com impulso.', createdAt: 0 },
  { id: 'ex-hams-11', name: 'Stiff Unilateral (Sem Peso)', muscleGroup: 'hamstrings', category: 'calisthenics', mediaFilename: 'Bodyweight_single_legged_romanian_deadlifts.mp4', instructions: 'Apoiado em uma perna, outra estendida atrás. Desça o tronco à frente em equilíbrio até paralelo. Volte estendendo o quadril.', createdAt: 0 },

  // GLÚTEOS (glutes) — 6
  { id: 'ex-glutes-01', name: 'Agachamento Búlgaro com Halteres', muscleGroup: 'glutes', category: 'strength', mediaFilename: 'dumbbell_bulgarian_split_squat.mp4', instructions: 'Pé de trás apoiado em banco, halteres ao lado. Desça flexionando o joelho da frente. Suba empurrando pela perna da frente.', createdAt: 0 },
  { id: 'ex-glutes-02', name: 'Hip Thrust no Smith', muscleGroup: 'glutes', category: 'strength', mediaFilename: 'Smithmachine_hip_thrust.mp4', instructions: 'Costas apoiadas no banco, barra do Smith sobre o quadril. Eleve o quadril contraindo glúteos até alinhar com tronco e coxas. Desça controlado.', createdAt: 0 },
  { id: 'ex-glutes-03', name: 'Glúteo Coice na Polia', muscleGroup: 'glutes', category: 'strength', mediaFilename: 'cable_glute_kickback.mp4', instructions: 'Polia baixa com tornozeleira em uma perna. Estenda a perna para trás contraindo o glúteo. Volte controlado sem balanço.', createdAt: 0 },
  { id: 'ex-glutes-04', name: 'Coice em Pé na Polia', muscleGroup: 'glutes', category: 'strength', mediaFilename: 'cable_standing_mid_kickback.mp4', instructions: 'Em pé na polia, tornozeleira em uma perna. Coice para trás contraindo o glúteo médio e máximo. Volte controlado.', createdAt: 0 },
  { id: 'ex-glutes-05', name: 'Abdução de Quadril na Polia', muscleGroup: 'glutes', category: 'strength', mediaFilename: 'cable_hip_abduction.mp4', instructions: 'Em pé com tornozeleira presa à polia baixa. Abra a perna lateralmente contraindo o glúteo médio. Volte controlado.', createdAt: 0 },
  { id: 'ex-glutes-06', name: 'Abdutor na Máquina', muscleGroup: 'glutes', category: 'strength', mediaFilename: 'machine_hip_abduction.mp4', instructions: 'Sentado na máquina, abra as pernas contra a resistência contraindo glúteo médio. Volte controlado.', createdAt: 0 },
];

const NOW = Date.now();
DEFAULT_EXERCISES.forEach(ex => { ex.createdAt = NOW; });
